function createfigure(X1, Y1, Y2, Y3, Y4, Y5, Y6)
%CREATEFIGURE(X1, Y1, Y2, Y3, Y4, Y5, Y6)
%  X1:  scatter x
%  Y1:  scatter y
%  Y2:  scatter y
%  Y3:  scatter y
%  Y4:  scatter y
%  Y5:  scatter y
%  Y6:  scatter y

%  Auto-generated by MATLAB on 18-Oct-2019 11:06:54

% Create figure
figure1 = figure;

% Create subplot
subplot1 = subplot(2,3,1,'Parent',figure1);
hold(subplot1,'on');

% Create scatter
scatter(X1,Y1,'Parent',subplot1);

% Create xlabel
xlabel('Sr');

% Create title
title('Viva');

% Create ylabel
ylabel('Viva');

% Create subplot
subplot2 = subplot(2,3,2,'Parent',figure1);
hold(subplot2,'on');

% Create scatter
scatter(X1,Y2,'Parent',subplot2);

% Create xlabel
xlabel('Sr');

% Create title
title('Sessional1');

% Create ylabel
ylabel('Sessional1');

% Create subplot
subplot3 = subplot(2,3,3,'Parent',figure1);
hold(subplot3,'on');

% Create scatter
scatter(X1,Y3,'Parent',subplot3);

% Create xlabel
xlabel('Sr');

% Create title
title('Sessional2');

% Create ylabel
ylabel('Sessional2');

% Create subplot
subplot4 = subplot(2,3,4,'Parent',figure1);
hold(subplot4,'on');

% Create scatter
scatter(X1,Y4,'Parent',subplot4);

% Create xlabel
xlabel('Sr');

% Create title
title('Total20');

% Create ylabel
ylabel('Total20');

% Create subplot
subplot5 = subplot(2,3,5,'Parent',figure1);
hold(subplot5,'on');

% Create scatter
scatter(X1,Y5,'Parent',subplot5);

% Create xlabel
xlabel('Sr');

% Create title
title('Total15');

% Create ylabel
ylabel('Total15');

% Create subplot
subplot6 = subplot(2,3,6,'Parent',figure1);
hold(subplot6,'on');

% Create scatter
scatter(X1,Y6,'Parent',subplot6);

% Create xlabel
xlabel('Sr');

% Create title
title('LabReports');

% Create ylabel
ylabel('LabReports');

